{{ $nerdFontVersion := "2.1.0" -}}
{{ $ageVersion := "1.0.0" -}}
{{ $lazyGitVersion := "0.34" -}}
{{ $lazyDockerVersion := "0.18.1" -}}
[".local/share/fonts/nerd-fonts/FiraCode"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $nerdFontVersion }}/FiraCode.zip"
    exact = true
    stripComponents = 1
[".local/share/fonts/nerd-fonts/UbuntuMono"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $nerdFontVersion }}/UbuntuMono.zip"
    exact = true
    stripComponents = 1
[".local/bin/age"]
    type = "file"
    url = "https://github.com/FiloSottile/age/releases/download/v{{ $ageVersion }}/age-v{{ $ageVersion }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/age".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "age/age"]
[".local/bin/lazygit"]
    type = "file"
    url = "https://github.com/jesseduffield/lazygit/releases/download/v{{ $lazyGitVersion }}/lazygit_{{ $lazyGitVersion }}_{{ .chezmoi.kernel.ostype }}_x86_64.tar.gz"
    executable = true
    [".local/bin/lazygit".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "lazygit"]
[".local/bin/lazydocker"]
    type = "file"
    url = "https://github.com/jesseduffield/lazydocker/releases/download/v{{ $lazyDockerVersion }}/lazydocker_{{ $lazyDockerVersion }}_{{ .chezmoi.kernel.ostype }}_x86_64.tar.gz"
    executable = true
    [".local/bin/lazydocker".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "lazydocker"]
